accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/<str:username>/",views.profile,name="profile"),
    path("login/",views.login_func,name="login"),
    path("logout/",views.logout_func,name="logout"),
    path("register/",views.register,name="register"),
    path("create_profile/",views.create_profile, name="create_profile"),
    path("add_experience/",views.add_exp,name="add_experience"),
    path("experience/delete/<int:id>",views.delete_exp,name="deleteexp"),
    path("profile_posts<str:username>",views.profile_posts,name="profile_posts"),
    path("follow/<str:username>",views.follow,name="follow"),
    path("unfollow/<str:username>",views.unfollow,name="unfollow"),
    path("followers_of_page",views.followers_of_page,name="followers_of_page"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name="index"),
    path("posts/",views.posts,name="posts"),
    path("sample/",views.sample,name="sample"),
    path("post/<int:id>",views.post,name="post"),
    path('post/delete/<int:id>',views.delete_post ,name='delete_post'),
    path('comment/delete/<int:id>',views.delete_comment ,name='delete_comment'),
    path('like_post/<int:id>',views.like_post ,name='like_post'),
    path('dislike_post/<int:id>',views.dislike_post,name='dislike_post'),
    # path("post/",views.post,name="post"),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('', include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import AbstractUser
from . managers import CustomUserManager
from django.urls import reverse
from django.contrib.auth import get_user_model

# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to = 'profile_picture', null=True, blank = True, default='profile_picture/defult.jpg')
    bio = models.TextField(null = True , blank = True)
    job = models.CharField(max_length=100, null = True , blank = True)
    location = models.CharField(max_length=500, default='location', null = True , blank = True)
    followers = models.ManyToManyField("self", blank=True, symmetrical=False, related_name='user_followers')
    objects = CustomUserManager()

    def total_followers(self):
        return self.followers.count()

    def get_absolute_url(self):
        return reverse("profile", kwargs={"username": self.username})


class SocialMedia(models.Model):
    KINDS = (
        ('w', 'web'),
        ('t', 'twiter'),
        ('f', 'facebook'),
        ('l', 'linkdin'),
        ('i', 'instagram'),
    )
    url = models.URLField()
    kinds = models.CharField(max_length = 1, choices = KINDS)
    user = models.ForeignKey(User,on_delete=models.CASCADE,)


class Skill(models.Model):
    name = models.CharField(max_length = 100)
    user = models.ManyToManyField(User)


class AddProfile(models.Model):
    picture = models.ImageField(null=True, blank = True,upload_to = 'profile_picture/',default='profile_picture/defult.jpg')
    job = models.CharField(max_length=200)
    company = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    location = models.CharField(max_length=200)
    skills = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='profile')



class Experience(models.Model):
    job_title = models.CharField(max_length=200)
    company = models.CharField(max_length=150)
    location = models.CharField(max_length=500)
    from_date = models.DateField()
    to_date = models.DateField()
    job_description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE) 


# user = get_user_model()

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm

class AddExperienceForm(forms.ModelForm):
    class Meta:
        model = models.Experience
        exclude = ['user']

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         exclude = ['user']

class UserForm(UserCreationForm):
    class Meta:
        model=models.User
        fields=['username','email']

class AddProfileForm(forms.ModelForm):
    class Meta:
        model=models.AddProfile
        fields="__all__"

class SocialMediaForm(forms.ModelForm):
    class Meta:
        model = models.SocialMedia
        exclude = ['user']

class SkillSetForm(forms.ModelForm):
    class Meta:
        model = models.Skill
        fields = ['name']

# class RegisterForm(forms.ModelForm):
#     class Meta:
#         model = Register
#         fields = ['name','username','password']

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from blog.forms import PostForm

from blog.models import Post,Comment
from .forms import AddExperienceForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import User,Experience,AddProfile



def register(request):
    if request.method == "POST":
        # name = request.POST['name']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username has already been taken')
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)
                return redirect('login')
        else:
            messages.info(request, 'two passwords do not match!')
            return redirect('register')

    return render(request, 'accounts/register.html', {})


@login_required
def profile(request, username):
    user=get_object_or_404(User,username=username)    
    return render(request, 'accounts/profile.html', {'user':user})


@login_required
def add_exp(request):
    if request.method == "POST":
        title = request.POST['title']
        company = request.POST['company']
        location = request.POST['location']
        from_date = request.POST['from']
        to = request.POST['to']
        description = request.POST['description']
        if title and location and from_date and to:
            exp = Experience(job_title=title, company=company, from_date=from_date, location=location,to_date=to, job_description=description)
            exp.user = request.user
            # exp = exp.save(commit = False)
            exp.save()
            # messages.SUCCESS(request, 'your experience has been saved!')
            return redirect('/profile/'+request.user.username)
        else:
            messages.info(request, ' fill out the form completly')
            return redirect('add-exp')

    return render(request, 'accounts/add-exp.html', {})


@login_required
def create_profile(request):
    # user_profile = AddProfile.objects.get(user=request.user)
    if request.method == "POST":
        job = request.POST['job']
        company = request.POST['company']
        website = request.POST['website']
        location = request.POST['location']
        skills = request.POST['skills']
        bio = request.POST['bio']
        pic = request.FILES.get('pic')
        # pic = request.POST['profilepic']
        if job and company and location and skills:
            pro = AddProfile(picture=pic, job=job, company=company, location=location, website=website, skills=skills, bio=bio, user=request.user)
            # pro.user = request.user
            pro.save()
            return redirect('/profile/'+request.user.username)

        else:
            messages.info(request, ' fill out the form completly')
            return redirect('create_profile')

    return render(request, 'accounts/create-profile.html', {})


def login_func(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(to=reverse('create_profile'))
        else:
            messages.add_message(request, messages.ERROR,
                                 "username or password is not correct")
    return render(request, 'accounts/login.html', {})


def logout_func(request):
    logout(request)
    return redirect(to=reverse('index'))



def delete_exp(request, id):
    exp = get_object_or_404(Experience ,id=id)
    if exp.user == request.user:
        exp.delete()
        messages.add_message(request,messages.SUCCESS,"Your post has been deleted!")
        # return redirect(to=reverse('profile'))
    else:
        pass
    return render(request, "accounts/profile.html", {})

def profile_posts(request, username):
    user=get_object_or_404(User,username=username)
    p = Post.objects.all()[:20]
    form = PostForm()
    return render(request, "accounts/profile_posts.html", {'user':user,'posts':p,'forms':form})

def follow(request, username):
    user = get_object_or_404(User, username=username)
    user.followers.add(request.user)
    # if request.user in user.followers.
    return redirect(request.META['HTTP_REFERER'])

def unfollow(request, username):
    user = get_object_or_404(User, username=username)
    user.followers.remove(request.user)
    # if request.user in user.followers.
    return redirect(request.META['HTTP_REFERER'])

def followers_of_page(request):
    u = User.objects.all()[:20]
    return render(request,'accounts/followers_of_page.html', {'users':u})

accounts/templates/accounts/add-exp.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{%static 'style.min copy2.css'%}" />
    <title>media</title>
  </head>
  <body style="background-image:linear-gradient(90deg, #002223, #0195a1);">
    <nav class="navbar bg-dark" style="background-image:linear-gradient(90deg,#f10202,#760202);">
      
      <h1>
        media
      </h1>
      <ul>
        {% if request.user.profile.picture %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.profile.picture.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% else %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="https://cdn5.vectorstock.com/i/thumb-large/45/59/profile-photo-placeholder-icon-design-in-gray-vector-37114559.jpg" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% endif %}
        <li><a href="{% url 'profile' username=request.user.username %}">profile</a></li>
        <li>
        </li>
        <li>
          <a href="{% url 'logout' %}" title="Logout">
            <span class="hide-sm">Logout</span></a
          >
        </li>
      </ul>
    </nav>
    <section class="container">
      <h1 class="large text-primary" style="color: white;">
        Add Experience
      </h1>
      <p class="lead" style="color:white ;">
        if your are a telented coffee maker. send us your experience.
      </p>
      <small style="color: white;">required field</small>
      <form class="form" method="post">
        {% csrf_token %}
        {% comment %} {% csrf_token %}
        {% for item in form %}
        <p style='color:white;'>{{item.label}}</p>
        {{item}}
        {% for error in item.errors %}
        <p style="color:rgb(248, 114, 114);">{{error}}</p>
        {% endfor %}
        {% endfor %} {% endcomment %}
        <div class="form-group">
          <input style="border-radius: 40px;" type="text" placeholder="* Job Title" name="title" required />
        </div> 
        <div class="form-group">
          <input style="border-radius: 40px;" type="text" placeholder="* Company" name="company" required/>
        </div>
        <div class="form-group">
          <input style="border-radius: 40px;" type="text" placeholder="Location" name="location"/>
        </div>
        <div class="form-group">
          <h4 style="color: white;">From Date</h4>
          <input type="date" name="from" style="border-radius: 40px;"> />
        </div>
        <div class="form-group">
          <h4 style="color: white;">To Date</h4>
          <input type="date" name="to" style="border-radius: 40px;"/>
        </div>
        <div class="form-group">
          <textarea
            name="description"
            cols="30"
            rows="5"
            placeholder="  Job Description"
            style="border-radius:50px ;"
          ></textarea>
        </div>
        <input type="submit" class="btn btn-primary my-1" style="border-radius: 40px;"> />
        <a style="border-radius:50px ;" class="btn my-1" href="{% url 'login' %}">Go Back</a>
      </form>
    </section>
    <h1>
      {% comment %} {{form}} {% endcomment %}
      {% comment %} {{job_title}}
      {{company}}
      {{location}}
      {{from_date}}
      {{to_date}}
      {{job_description}} {% endcomment %}
    </h1>
  </body>
</html>

accounts/templates/accounts/create-profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{%static 'style.min copy.css'%}" />
    <title>media</title>
  </head>
  <body style="background-image:linear-gradient(90deg, #002223, #0195a1);">
    <nav class="navbar bg-dark" style="background-image:linear-gradient(90deg,#f10202,#760202);">
      <h1>
        Media
      </h1>
      <ul>
      


        {% if request.user.profile.picture %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.profile.picture.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% else %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.pic.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% endif %}



        <li><a href="{% url 'profile' username=request.user.username %}">profile</a></li>
        <li><a href="{% url 'posts' %}">posts</a></li>
        <li><a href="{% url 'add_experience' %}">add experience</a></li>
        <li>
          <a href="{% url 'logout' %}">
            <span class="hide-sm"> Logout</span></a
            >
          </li>
      </ul>
    </nav>
    <section class="container">
      <h1 class="large text-primary" style="color: rgb(223, 221, 221);">
        Create Your Profile
      </h1>
      <h2 style="color: rgb(218, 214, 214);">
        welcome {{user.username}}
      </h2>
      <p class="lead" style="color:white;">
        <b>create your profile</b>
      </p>
      <small style="color: rgb(227, 225, 225)">required fields</small>
      <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          <b><label for="profile pic" style="color:white; width:100px;">choose your profile picture</label></b>
          <input value="profile picture" style="background-color:rgb(235, 224, 224) ;border-radius:50px;width:1030px; height:30px;" type="file" placeholder="profile pic" name="pic" />
        </div>


        <div class="form-group">
          <input style="background-color:rgb(235, 224, 224) ;border-radius:50px;" type="text" placeholder="job" name="job" />
        </div>
        <div class="form-group">
          <input style="background-color:rgb(235, 224, 224) ;border-radius:50px;" type="text" placeholder="Company" name="company" />
          <small class="form-text"style="color: white;"
            >Could be your own company or one you work for</small
          >
        </div>
        <div class="form-group">
          <input style="background-color:rgb(231, 219, 219) ;border-radius:50px;" type="text" placeholder="Website" name="website" />
          <small class="form-text"style="color: white;"
            >Could be your own or a company website</small
          >
        </div>
        <div class="form-group">
          <input style="background-color:rgb(230, 218, 218);border-radius:50px;" type="text" placeholder="Location" name="location" />
          <small class="form-text"style="color: white;"
            >City & state suggested (eg. Boston, MA)</small
          >
        </div>
        <div class="form-group">
          <input style="background-color:rgb(232, 221, 221) ;border-radius:50px;" type="text" placeholder="* Skills" name="skills" />
          <small class="form-text"style="color: white;"
            >Please separate with comma (eg.
            food,sperso,late,coffee)</small
          >
        </div>
          
          
        <div class="form-group">
          <textarea style="background-color:rgb(235, 224, 224) ;border-radius:50px;" placeholder="A short bio of yourself" name="bio"></textarea>
          <small class="form-text"style="color: white;">Tell us a little about yourself</small>
        </div>

        <input type="submit" class="btn btn-primary my-1" style="border-radius:5px ; position: relative; bottom: 30px;" />
        <a class="btn btn-light my-1" href="{% url 'login' %}" style="border-radius:5px; position: relative; bottom: 30px;background-color: rgb(202, 212, 65);">Go Back</a>
      </form>
    </section>
  </body>
</html>

accounts/templates/accounts/followers_of_page.html
{% comment %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.min copy2.css'%}" />
    <title>media</title>
  </head>
  <body style="background-image:linear-gradient(90deg, #002223, #0195a1);">
    <nav class="navbar bg-dark" style="background-image:linear-gradient(90deg,#e00101,#760202);">
        <h1>
          Media
        </h1>
        <ul>
          {% if request.user.profile.picture %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.profile.picture.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% else %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.pic.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% endif %}
          <li>{{request.user.username}}</li>
          <li><a href="{% url 'logout' %}">logout</a></li>
          <li><a href="{% url 'posts' %}">posts</a></li>
  
        </ul>
      </nav>    
      <br><br><br><br>
      {% for user in users %}
      {% if user in user.followers.all %}
      <div class="posts" style="width:70%;">
          
        <div class="post bg-white my-1 p-1" style="border-radius:200px ;">

          <div>



            <a href="{% url 'profile' username=user.username %}">
              {% if user.profile.picture %}
              <img
                class="round-img"
                src="{{user.profile.picture.url}}"
                alt="picture of user"
              />
              {% else %}
              <img
                class="round-img"
                src="{{user.pic.url}}"
                alt="picture of user"
                
              />
              {% endif %}
              <h3>{{user.username}}</h3>
            </a>
          </div>
          <a href="{% url 'profile' username=user.username %}" class="btn" style="width:200px; height:30px;background-color:rgb(147, 147, 147);border-radius: 100px; ">check this profile!</a>
          <h2 style="color:black; position: relative;left: 260px; bottom:50px;">{{user.followers.count}} followers</h2>

  
          </div>
        </div>
        </div>
        {% endif %}
      {% endfor %}

</body>
</html> {% endcomment %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{%static 'style.min.css' %}" />
    <title>media</title>
  </head>
  <body style="background-image:linear-gradient(90deg, #002223, #0195a1);">
    <nav class="navbar bg-dark" style="background-image:linear-gradient(90deg,#e00101,#760202);">
      <h1>
        Media
      </h1>
      <ul>
        <li><a href="{% url 'register' %}">Register</a></li>
        <li><a href="{% url 'logout' %}">logout</a></li>
      </ul>
      
    </nav>
    <section class="container">
      <!-- Alert -->
      {% comment %} {% if messages %}
      {% for message in messages %}
      <div style="background-color:red ;color: aliceblue;width:300px; height:50px;">{{message}}</div>
      
      {% endfor %}
      {% endif %} {% endcomment %}
      <h1 class="large text-primary">
        Login
      </h1>
      <p class="lead"> Enter your account</p> 
      <form action="{% url 'login' %}" class="form1" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input name="username" id="emaillog" type="username" placeholder="  Username" style="border-radius:40px ;">
        </div>
        <div class="form-group">
          <input name="password" id="passlog" type="password" placeholder="  Password" style="border-radius:40px ;">
        </div>
        <input id="btnlog" type="submit" value="Login" class="btn btn-primary" style="border-radius:40px ;">
      </form>
      <p class="my-1">
        You don't have an account? <a href="{% url 'register' %}" style="color:rgb(215, 252, 4) ;">Sign Up</a>
      </p>
    </section>
  </body>
</html>

accounts/templates/accounts/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{%static 'style.min.css'%}" />
    <title>meida</title>
  </head>
  <body style="background-image:linear-gradient(90deg, #002223, #0195a1);">
    <nav class="navbar bg-dark" style="background-image:linear-gradient(90deg,#e00101,#760202);">
      <h1>
        Meida
      </h1>
      <ul>
        {% if request.user.profile.picture %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="{{request.user.profile.picture.url}}" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% else %}
        <li><a href="{% url 'profile' username=request.user.username %}">
          <img src="https://cdn5.vectorstock.com/i/thumb-large/45/59/profile-photo-placeholder-icon-design-in-gray-vector-37114559.jpg" alt="profile pic" style="width:50px;height:50px;border-radius:100px;">
        </li></a>
        {% endif %}

        <li>{{user.username}}</li>
        <li><a href="{% url 'logout' %}">logout</a></li>
        <li><a href="{% url 'posts' %}">posts</a></li>
        <li><a href="{% url 'add_experience' %}">add experience</a></li>

      </ul>
    </nav>
    <section class="container">
      <a style='border-radius:50px;' href="{% url 'create_profile' %}" class="btn">go back to create profile</a>


      {% if user != request.user %}

        {% if request.user not in user.followers.all %}
          <a style='border-radius:50px;background-color: chartreuse;' href="{% url 'follow' username=user.username %}" class="btn">Follow</a>
        {% else %}
          <a style='border-radius:50px;background-color: rgb(250, 96, 96); color: white;' href="{% url 'unfollow' username=user.username %}" class="btn">Unfollow</a>
        {% endif %}

      {% endif %}

      <a style="border-radius:0px;color:black; position: relative;left: 200px; background-image: linear-gradient(90deg, rgb(203, 186, 186),rgb(238, 227, 227), rgb(192, 174, 174),rgb(236, 226, 226),rgb(192, 174, 174));" href="" class="btn">{{user.followers.count}} followers</a>





      <!-- <h1 style="color:white;"><big><big>{{user.followers.count}}</big></big></h1> -->
      <div class="profile-grid my-1">
        <!-- Top -->
        {% if user.profile.picture %}
        <div class="profile-top bg-primary p-2"  style="background-image: linear-gradient(144deg,rgb(149, 0, 255),rgb(221, 3, 228)) ; border-radius:500px ;width: 1000px;">
          <img
          style="border-radius:300px;"
          class="prof"
          src="{{user.profile.picture.url}}"
          alt="user picture"
          />
          {% else %}
          <div class="profile-top bg-primary p-2"  style="background-image: linear-gradient(144deg,rgb(149, 0, 255),rgb(221, 3, 228)) ; border-radius:500px ;width: 1000px;">
          <img
            style="border-radius:300px;"
            class="prof"
            src="{{user.pic.url}}"
            alt="user picture"
          />

        {% endif %}
      
          <h1 class="large">{{user.username}}</h1>
          <h1>{{user.get_full_name}}</h1>

          <h3 style="position:relative;top:30px ;">{{user.profile.location}}</h3>
          {% if user.profile.job %}
          <p class="leadprof">{{user.profile.job}}</p>
          {% endif %}
          <b><a style="border-radius:50px;" href="{% url 'profile_posts' username=user.username %}" type='submit' class="btn">{{user.username}}'s posts</a></b>
          <div class="icons my-1">


            {% if user.socialmedia_set.all %}
            {% for media in user.socialmedia_set.all %}

            {% if media.kinds == 'w' %}
            <a href="{{media.url}}">
              <i class="fas fa-globe fa-2x"></i>
            </a>
            {% elif media.kinds == 't' %}
            <a href="{{media.url}}">
              <i class="fab fa-twitter fa-2x"></i>
            </a>
            {% elif media.kinds  == 'f' %}
            <a href="{{media.url}}">
              <i class="fab fa-facebook fa-2x"></i>
            </a>
            {% elif media.kinds == 'l' %}

            <a href="{{media.url}}">
              <i class="fab fa-linkedin fa-2x"></i>
            </a>
            {% elif media.kinds == 'i' %}

            <a href="{{media.url}}">
              <i class="fab fa-instagram fa-2x"></i>
            </a>
            {% endif %}
            {% endfor %}
            {% endif %}
          </div>
        </div>
        <!-- About -->
        

        
        <div class="profile-exp bg-white p-2" style="width: 1000px;background-color:rgb(216, 243, 117) ;border-radius: 110px;">
          <h2 class="text-primary"></h2>
          <h2>experiences:</h2><br>
          {% if user.experience_set.all %}
          <hr>
          {% for exp in user.experience_set.all %}
          <div>
            <h3>{{exp.job_title}}</h3>
            <p>{{exp.from_date}} - {{exp.to_date}}</p>
            <p><strong>company: </strong>{{exp.company}}</p>
            <p>
              <strong>Description: </strong>{{exp.job_description}}
            </p>
            {% if request.user == exp.user %}
            <a href="{% url 'deleteexp' id=exp.id %}" class='btn btn-danger' style='border-radius:50px;'>Delete</a>
            {% endif %}
          </div>
          <hr>
          {% endfor %}
          {% endif %}
          <div>




          </div>
        </div>
        <div class="profile-about bg-light p-2" style="background-color:rgb(89, 207, 239) ;border-radius: 160px;">
          {% if user.profile.bio %}
          <h2>bio</h2>
          <p>
            {{user.profile.bio}}
          </p>
          {% endif %}
          <div class="line"></div>
          {% if user.profile.skills %}
          <p><h2>skills</h2></p>
          {% comment %} {% for skill in user.profile.skills %} {% endcomment %}
          
            <div class="p-1">{{user.profile.skills}}</div>
        
            {% comment %} {% endfor %} {% endcomment %}
            
            {% endif %}
        </div>
  </body>
</html>